version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - apt update
      - apt install -y nodejs npm

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - node app.js
artifacts:
  files:
    - '**/*'
